services:

  backend:
    build: .
    container_name: webhook_backend

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - redis

    volumes:
      - .:/app

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker-high:
    build: .
    container_name: webhook_worker_high
    command: celery -A worker.celery_app:celery worker --loglevel=info --concurrency=4 -Q high_priority
    ports:
      - "8001:8001"
    environment:
        - METRICS_PORT=8001
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app

  worker-retry:
    build: .
    container_name: webhook_worker_retry
    command: celery -A worker.celery_app:celery worker --loglevel=info --concurrency=2 -Q default,low_priority
    ports:
      - "8002:8002"
    environment:
        - METRICS_PORT=8002
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app

  redis:
    image: redis:7-alpine
    container_name: webhook_redis

    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    container_name: webhook_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend
      - worker-high
      - worker-retry

  grafana:
    image: grafana/grafana:latest
    container_name: webhook_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

volumes:
  grafana_data: