"""add tenant usage counters

Revision ID: 11f3af4ac332
Revises: 355494f53fe9
Create Date: 2026-05-28 11:49:34.874637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f3af4ac332'
down_revision: Union[str, Sequence[str], None] = '355494f53fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('events_sent_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('tenants', sa.Column('delivery_attempts_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('tenants', sa.Column('retries_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'retries_count')
    op.drop_column('tenants', 'delivery_attempts_count')
    op.drop_column('tenants', 'events_sent_count')
    # ### end Alembic commands ###
