"""add webhook secret to tenants

Revision ID: 1261d0b1bb96
Revises: f44883f72b98
Create Date: 2026-05-18 11:04:48.090834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1261d0b1bb96'
down_revision: Union[str, Sequence[str], None] = 'f44883f72b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('webhook_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'webhook_secret')
    # ### end Alembic commands ###
