"""add_health_monitoring_fields

Revision ID: 355494f53fe9
Revises: 3d4bf8aae007
Create Date: 2026-05-23 13:44:52.045463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '355494f53fe9'
down_revision: Union[str, Sequence[str], None] = '3d4bf8aae007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circuit_breakers', sa.Column('success_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('circuit_breakers', sa.Column('total_requests', sa.Integer(), server_default='0', nullable=False))
    op.add_column('circuit_breakers', sa.Column('success_rate', sa.Float(), server_default='100.0', nullable=False))
    op.add_column('circuit_breakers', sa.Column('average_latency_ms', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('circuit_breakers',
                  sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False))
    op.add_column('circuit_breakers', sa.Column('health_score', sa.Float(), server_default='100.0', nullable=False))
    op.add_column('circuit_breakers', sa.Column('health_state', sa.String(), server_default='healthy', nullable=False))

    op.alter_column('dead_letter_events', 'original_event_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('dead_letter_events', 'failure_type',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('dead_letter_events', 'final_error',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.create_index(op.f('ix_dead_letter_events_id'), 'dead_letter_events', ['id'], unique=False)
    op.alter_column('delivery_attempts', 'attempt_number',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.create_index(op.f('ix_delivery_attempts_id'), 'delivery_attempts', ['id'], unique=False)
    op.drop_constraint('events_idempotency_key_key', 'events', type_='unique')
    op.create_unique_constraint('uq_tenant_idempotency', 'events', ['tenant_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # This just drops the columns, so it doesn't need defaults
    ...
    op.drop_column('circuit_breakers', 'health_state')
