"""production_refactor

Revision ID: 83faf0c1045a
Revises: 11f3af4ac332
Create Date: 2026-05-29 15:30:18.892520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83faf0c1045a'
down_revision: Union[str, Sequence[str], None] = '11f3af4ac332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('failure_type', sa.String(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_deliveries_id'), 'subscription_deliveries', ['id'], unique=False)
    op.drop_index(op.f('ix_circuit_breakers_endpoint_url'), table_name='circuit_breakers')
    op.create_index(op.f('ix_circuit_breakers_endpoint_url'), 'circuit_breakers', ['endpoint_url'], unique=False)
    op.create_unique_constraint('uq_tenant_endpoint', 'circuit_breakers', ['tenant_id', 'endpoint_url'])
    op.create_foreign_key(None, 'circuit_breakers', 'tenants', ['tenant_id'], ['id'])
    op.add_column('dead_letter_events', sa.Column('subscription_delivery_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dead_letter_events', 'subscription_deliveries', ['subscription_delivery_id'], ['id'])
    op.create_foreign_key(None, 'subscriptions', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'dead_letter_events', type_='foreignkey')
    op.drop_column('dead_letter_events', 'subscription_delivery_id')
    op.drop_constraint(None, 'circuit_breakers', type_='foreignkey')
    op.drop_constraint('uq_tenant_endpoint', 'circuit_breakers', type_='unique')
    op.drop_index(op.f('ix_circuit_breakers_endpoint_url'), table_name='circuit_breakers')
    op.create_index(op.f('ix_circuit_breakers_endpoint_url'), 'circuit_breakers', ['endpoint_url'], unique=True)
    op.drop_index(op.f('ix_subscription_deliveries_id'), table_name='subscription_deliveries')
    op.drop_table('subscription_deliveries')
    # ### end Alembic commands ###
